#!/usr/bin/env bash
# IcarusEye v2 — Cross-platform setup script
# Detects your hardware and writes docker-compose.override.yml + .env
set -euo pipefail

BOLD='\033[1m'
CYAN='\033[0;36m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
NC='\033[0m'

info()    { echo -e "${CYAN}[setup]${NC} $*"; }
success() { echo -e "${GREEN}[setup]${NC} $*"; }
warn()    { echo -e "${YELLOW}[setup]${NC} $*"; }
error()   { echo -e "${RED}[setup]${NC} $*" >&2; }

# ── Platform detection ────────────────────────────────────────────────────────

OS=$(uname -s)
ARCH=$(uname -m)
PLATFORM="cpu"  # default

is_jetson() {
    if [ -f /proc/device-tree/model ]; then
        grep -qi "nvidia jetson" /proc/device-tree/model 2>/dev/null && return 0
    fi
    command -v tegrastats >/dev/null 2>&1 && return 0
    return 1
}

has_nvidia_gpu() {
    command -v nvidia-smi >/dev/null 2>&1 && nvidia-smi -L >/dev/null 2>&1
}

has_docker() {
    command -v docker >/dev/null 2>&1
}

has_nvidia_container_toolkit() {
    docker info 2>/dev/null | grep -q "Runtimes.*nvidia"
}

# ── Detect ────────────────────────────────────────────────────────────────────

echo -e "${BOLD}IcarusEye v2 — Setup${NC}"
echo "─────────────────────────────────────────"
info "OS:   $OS"
info "Arch: $ARCH"

if [ "$OS" = "Darwin" ]; then
    warn "macOS detected — Docker Desktop does not support NVIDIA runtime."
    warn "Running in CPU / dev mode (mock inference, file source)."
    PLATFORM="cpu"
elif is_jetson; then
    success "NVIDIA Jetson detected."
    PLATFORM="jetson"
elif has_nvidia_gpu; then
    if [ "$ARCH" = "x86_64" ] || [ "$ARCH" = "amd64" ]; then
        success "NVIDIA GPU detected on x86_64."
        if ! has_nvidia_container_toolkit; then
            warn "nvidia-container-toolkit not found in Docker runtimes."
            warn "Install it from https://docs.nvidia.com/datacenter/cloud-native/container-toolkit/install-guide.html"
            warn "Falling back to CPU / dev mode for now."
            PLATFORM="cpu"
        else
            PLATFORM="gpu"
        fi
    else
        warn "NVIDIA GPU detected on $ARCH (non-Jetson) — falling back to CPU mode."
        PLATFORM="cpu"
    fi
else
    info "No NVIDIA GPU found. Using CPU / dev mode (mock inference)."
    PLATFORM="cpu"
fi

echo ""

# ── Write docker-compose.override.yml ────────────────────────────────────────

OVERRIDE="docker-compose.override.yml"

case "$PLATFORM" in
    jetson)
        info "Writing $OVERRIDE for Jetson..."
        cp docker-compose.jetson.yml "$OVERRIDE"
        ;;
    gpu)
        info "Writing $OVERRIDE for x86_64 NVIDIA GPU..."
        cp docker-compose.gpu.yml "$OVERRIDE"
        ;;
    cpu)
        info "Writing $OVERRIDE for CPU / dev mode..."
        # CPU is the base docker-compose.yml default; override is a no-op passthrough
        cat > "$OVERRIDE" <<'EOF'
# IcarusEye v2 — CPU / dev mode (generated by setup.sh)
# No GPU hardware required. Mock inference enabled via DEV_MODE=true.
services:
  pipeline:
    environment:
      - DEV_MODE=true
EOF
        ;;
esac

success "Wrote $OVERRIDE (platform: $PLATFORM)"

# ── Write .env if missing ─────────────────────────────────────────────────────

if [ ! -f .env ]; then
    info "Creating .env from .env.example..."
    cp .env.example .env
    success "Created .env — edit it to set HLS_SOURCE, CAPTURE_TYPE, etc."
else
    info ".env already exists — skipping."
fi

# ── Sample directory hint ─────────────────────────────────────────────────────

if [ "$PLATFORM" = "cpu" ] && [ ! -d sample ]; then
    echo ""
    warn "DEV_MODE uses a file source. Drop a video into sample/ and set:"
    warn "  HLS_SOURCE=/app/sample/yourfile.mp4  (in .env)"
fi

# ── Summary ───────────────────────────────────────────────────────────────────

echo ""
echo "─────────────────────────────────────────"
success "Setup complete! Platform: ${BOLD}${PLATFORM}${NC}"
echo ""
echo -e "  Start:  ${BOLD}docker-compose up --build${NC}"
echo -e "  UI:     ${BOLD}http://localhost:8080${NC}"
echo ""

if [ "$PLATFORM" = "gpu" ] || [ "$PLATFORM" = "jetson" ]; then
    echo -e "  To export a YOLO model to TensorRT engine:"
    echo -e "  ${BOLD}python models/export_tensorrt.py${NC}"
    echo ""
fi
