model:
  yolov8s: "models/yolov8s.pt"
  deepsort: "models/deepsort_model.tflite"

video:
  live: false
  device: 0
  source: "test_flight.mp4"
  target_fps: 60
  nth_frame: 5  # Adjust workload

detection:
  confidence_threshold: 0.0  # Minimum confidence for displaying boxes
  omit_classes: []

output:
  save_video: true
  output_path: "output/detected_video.mp4"