model:
  yolov8s: "models/yolov8s.pt"
  deepsort: "models/deepsort_model.tflite"

video:
  live: true
  device: 0
  source: "./input.mp4"
  target_fps: 60
  nth_frame: 5  # Adjust workload

output:
  save_video: true
  output_path: "outputs/detected_video.mp4"