model:
  yolov8s: "models/yolov8s.pt"
  yolov8s_pretrained: "models/pretrained-yolov8s.pt"
  deepsort: "models/deepsort/mars-small128.pb"  # Path to DeepSORT embedder model

video:
  live: false
  device: 0
  source: "test_flight.mp4"
  target_fps: 30
  nth_frame: 7  # Adjust workload
  max_labels: 20

detection:
  confidence_threshold: 0.2  # Minimum confidence for displaying boxes
  omit_classes: []

tracker:
  max_cosine_distance: 0.2  # Max cosine distance for association
  nn_budget: 100            # Maximum size of the feature extractor queue
  max_age: 30               # Maximum number of missed detections before a track is deleted
  n_init: 3                 # Number of frames to confirm a track

logging:
  detection_verbose: false
  level: "WARNING"  # 0: OFF, 1: DEBUG, 2: INFO, 3: WARNING

output:
  save_video: true
  output_path: "output/detected_video.mp4"

class_details:
  0:
    class: pedestrian
    value: [255, 125, 0]
    name: orange
  1:
    class: people
    value: [255, 125, 0]
    name: orange
  2:
    class: bicycle
    value: [255, 125, 0]
    name: orange
  3:
    class: car
    value: [0, 255, 0]
    name: green
  4:
    class: van
    value: [0, 255, 0]
    name: green
  5:
    class: truck
    value: [0, 255, 0]
    name: green
  6:
    class: tricycle
    value: [0, 255, 0]
    name: green
  7:
    class: awning-tricycle
    value: [0, 255, 0]
    name: green
  8:
    class: bus
    value: [0, 255, 0]
    name: green
  9:
    class: motor
    value: [0, 255, 0]
    name: green