model:
  yolov8s: "models/yolov8s.pt"
  yolov8s_pretrained: "models/pretrained-yolov8s.pt"
  deepsort: "models/deepsort/mars-small128.pb"  # Path to DeepSORT embedder model

video:
  live: true
  device: 0
  source: "goggles_test.mp4"
  target_fps: 30
  nth_frame: 3  # Adjust workload
  max_labels: 5

detection:
  confidence_threshold: 0.2  # Minimum confidence for displaying boxes
  omit_classes: []

tracker:
  max_cosine_distance: 0.2  # Max cosine distance for association
  nn_budget: 100            # Maximum size of the feature extractor queue
  max_age: 30               # Maximum number of missed detections before a track is deleted
  n_init: 3                 # Number of frames to confirm a track

logging:
  detection_verbose: false
  level: "WARNING"  # 0: OFF, 1: DEBUG, 2: INFO, 3: WARNING

output:
  save_video: true
  output_path: "output/detected_video.mp4"

class_names:
  0: pedestrian
  1: people
  2: bicycle
  3: car
  4: van
  5: truck
  6: tricycle
  7: awning-tricycle
  8: bus
  9: motor

colors:
  0: [255, 125, 0]
  1: [255, 125, 0]
  2: [255, 125, 0]
  3: [0, 255, 0]
  4: [0, 255, 0]
  5: [0, 255, 0]
  6: [0, 255, 0]
  7: [0, 255, 0]
  8: [0, 255, 0]
  9: [0, 255, 0]