model:
  yolov8s: "models/yolov8s.pt"
  yolov8s_pretrained: "models/yolov8s_pretrained.pt"
  deepsort: "models/deepsort_model.tflite"

video:
  live: true
  device: 0
  source: "test_flight.mp4"
  target_fps: 60
  nth_frame: 5  # Adjust workload

detection:
  confidence_threshold: 0.0  # Minimum confidence for displaying boxes
  omit_classes: []

logging:
  detection_verbose: false
  level: 0 # 0: OFF, 1: DEBUG, 2: INFO, 3: WARNING

output:
  save_video: true
  output_path: "output/detected_video.mp4"