model:
  yolov8s: "models/yolov8s.pt"
  deepsort: "models/deepsort_model.tflite"

video:
  live: true
  device: 0
  source: "./input.mp4"
  target_fps: 60
  nth_frame: 10  # Adjust workload

detection:
  confidence_threshold: 0.3  # Minimum confidence for displaying boxes
  omit_classes: [59]

output:
  save_video: true
  output_path: "outputs/detected_video.mp4"