# Paths for VisDrone dataset (pointing directly to images and annotations)
visdrone-train: dataset/raw/VisDrone2019-DET-train/images       # Path to training images
visdrone-val: dataset/raw/VisDrone2019-DET-val/images           # Path to validation images
visdrone-test: dataset/raw/VisDrone2019-DET-test/images         # Path to test images

# Paths for annotations
train_annotations: dataset/raw/VisDrone2019-DET-train/annotations   # Path to training annotations
val_annotations: dataset/raw/VisDrone2019-DET-val/annotations       # Path to validation annotations
test_annotations: dataset/raw/VisDrone2019-DET-test/annotations     # Path to test annotations


# Paths for processed images and labels
train: dataset/images/input/train                     # Path to training images
val: dataset/images/input/val                         # Path to validation images
test: dataset/images/input/test                       # Path to test images

train_labels: dataset/images/labels/train             # Path to YOLO training labels
val_labels: dataset/images/labels/val                 # Path to YOLO validation labels
test_labels: dataset/images/labels/test               # Path to YOLO test labels

# (Future) Paths for videos
video_input: dataset/videos/input                     # Path to input videos (optional)
video_labels: dataset/videos/labels                   # Path to video labels (optional)


nc: 10                             # Number of classes (adjust for your dataset)
names: ['car', 'person', 'truck', ...]  # List of class names

# Hyperparameters for training
epochs: 100
batch_size: 16
img_size: 640                      # Input image size
augmentation:
  flip: true
  scale: 0.5                       # Scale images by +/- 50%
  jitter: 0.3                      # Jitter colors
